name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache node assets
        id: cache-node
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install node dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install

      - name: Run CI pass
        run: npm run ci

      - name: Build site
        run: npm run build

      - name: Use CNAME file if present
        run: "[ -e CNAME ] && cp CNAME dist"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
